### ISSUE TITLE
read_msa assumes that .fasta files have no line breaks

### ISSUE THREAD

**Issue by htalibart** [anna-pa-m/adabmDCA#1]
Hi!

I was trying to run adabmDCA on one of my .fasta file, which is formatted with at most 60 characters per line, and I noticed that, while my MSA has 73 columns, the first line outputted by adabmDCA was "M = 25 L = 60 q = 21". I tried changing the fasta file so that there was no line break and then it worked fine ("M = 25 L = 73 q = 21").

I think the problem is in the line `else if (ch == '\n' && newseq == 0 && readseq == 1)` in read_msa: the function assumes that there is no line break in fasta files, while often there is.

I can see that it makes it harder to parse input files, if you don't want to deal with it maybe you could be more precise on the format required by adabmDCA in the documentation?

**Comment by anna-pa-m** [comment]
Hi Hugo! Thank you for pointing at it. You are right, there is an issue while reading this kind of FASTA file. We are aware of this problem, we are working on that (I'll push a solution very soon). Thank you again.

**Comment by anna-pa-m** [comment]
Done!
